// Mocks generated by Mockito 5.4.6 from annotations
// in cash_flow/test/helpers/mock_repositories.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cash_flow/features/auth/domain/repositories/auth_repository.dart'
    as _i7;
import 'package:cash_flow/features/auth/model/user_model.dart' as _i3;
import 'package:cash_flow/features/categories/domain/repositories/category_repository.dart'
    as _i8;
import 'package:cash_flow/features/categories/model/category_model.dart' as _i9;
import 'package:cash_flow/features/settings/domain/repositories/settings_repository.dart'
    as _i10;
import 'package:cash_flow/features/transactions/domain/repositories/transaction_repository.dart'
    as _i4;
import 'package:cash_flow/features/transactions/model/cash_flow_summary_model.dart'
    as _i2;
import 'package:cash_flow/features/transactions/model/transaction_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCashFlowSummaryModel_0 extends _i1.SmartFake
    implements _i2.CashFlowSummaryModel {
  _FakeCashFlowSummaryModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i4.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> addTransaction(_i6.TransactionModel? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.TransactionModel>> getTransactions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [userId]),
            returnValue: _i5.Future<List<_i6.TransactionModel>>.value(
              <_i6.TransactionModel>[],
            ),
          )
          as _i5.Future<List<_i6.TransactionModel>>);

  @override
  _i5.Future<List<_i6.TransactionModel>> getTransactionsByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByDateRange, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i5.Future<List<_i6.TransactionModel>>.value(
              <_i6.TransactionModel>[],
            ),
          )
          as _i5.Future<List<_i6.TransactionModel>>);

  @override
  _i5.Future<void> deleteTransaction(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [transactionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.CashFlowSummaryModel> getCashFlowSummary(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCashFlowSummary, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i5.Future<_i2.CashFlowSummaryModel>.value(
              _FakeCashFlowSummaryModel_0(
                this,
                Invocation.method(#getCashFlowSummary, [
                  userId,
                  startDate,
                  endDate,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.CashFlowSummaryModel>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UserModel> register(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, password]),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#register, [username, password]),
              ),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<_i3.UserModel> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i3.UserModel?>.value(),
          )
          as _i5.Future<_i3.UserModel?>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i8.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<List<_i9.CategoryModel>>.value(
              <_i9.CategoryModel>[],
            ),
          )
          as _i5.Future<List<_i9.CategoryModel>>);

  @override
  _i5.Future<_i9.CategoryModel?> getCategoryById(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [categoryId]),
            returnValue: _i5.Future<_i9.CategoryModel?>.value(),
          )
          as _i5.Future<_i9.CategoryModel?>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i10.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> changeLanguage(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [languageCode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getLanguage() =>
      (super.noSuchMethod(
            Invocation.method(#getLanguage, []),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#getLanguage, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> updateAvatar(String? avatarPath) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatar, [avatarPath]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAvatarPath() =>
      (super.noSuchMethod(
            Invocation.method(#getAvatarPath, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveCurrentUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#saveCurrentUserId, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getCurrentUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserId, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearCurrentUserId() =>
      (super.noSuchMethod(
            Invocation.method(#clearCurrentUserId, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
